### ISSUE TITLE
Datomic dependency issue

### ISSUE THREAD

**Issue by belucid** [cloojure/tupelo#4]
Adding [tupelo "0.1.56"] to my project results in a datomic dependency error:

```
lein deps
Retrieving tupelo/tupelo/0.1.56/tupelo-0.1.56.pom from clojars
Retrieving criterium/criterium/0.4.3/criterium-0.4.3.pom from clojars
Retrieving criterium/criterium/0.4.3/criterium-0.4.3.jar from clojars
Retrieving tupelo/tupelo/0.1.56/tupelo-0.1.56.jar from clojars
Could not find artifact com.datomic:datomic-pro:jar:0.9.5173 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.datomic:datomic-pro:jar:0.9.5173 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
```

**Comment by cloojure** [comment]
Hi - Thanks for letting me know about the dependency problem with datomic-pro. Since I have it installed, here, I never saw that error.

I'm going to break out the datomic functionality into a new ns, "tupelo-datomic.core" in a separate repo.  As soon as I can push the changes (later tonight), the plain tupelo repo should be conflict free.

Alan

**Comment by cloojure** [comment]
Hi - I pushed a new version of tupelo (w/o any datomic stuff) to clojars.  Please try version 0.1.58 and let me know the result.

Thanks!
Alan

**Comment by cloojure** [comment]
Make that 0.1.59   :)
Alan

**Comment by belucid** [comment]
That worked. Thanks Alan!

**Comment by cloojure** [comment]
Hey - Thank you for letting me know about it.  That problem has probably been in there for 6 months (since I first added the Datomic stuff) and I never knew it.
